<?php /** @var \Handy\Profiler\Block\Queries $block */ ?>

<table cellpadding='0' cellspacing='0' border='1'>
    <tr>
        <th style="font-family: Courier; padding: 2px 4px; font-size: 11px">
            Time
            <br/>Total:&nbsp;<?=number_format($block->getProfiler()->getTotalElapsedSecs(),4)?>&nbsp;secs
        </th>
        <th style="font-family: Courier; padding: 2px 4px; font-size: 11px">
            Query
            <br />Total:&nbsp;<?=$block->getProfiler()->getTotalNumQueries()?>&nbsp;queries
        </th>
        <th style="font-family: Courier; padding: 2px 4px; font-size: 11px">
            Query Params
        </th>
    </tr>
    <?php foreach ( $block->getQueries() as $query ) { ?>
    <tr>
        <td style="font-family: Courier; padding: 2px 4px; font-size: 11px">
            <?=number_format(1000 * $query->getElapsedSecs(), 2)?> ms
        </td>
        <td style="font-family: Courier; padding: 2px 4px; font-size: 11px">
            <?=$block->colorize($query->getQuery())?>
        </td>
        <td style="font-family: Courier; padding: 2px 4px; font-size: 11px">
            <?=json_encode($query->getQueryParams(),JSON_PRETTY_PRINT)?>
        </td>
    </tr>
    <?php } ?>
</table>
